#!/usr/bin/env bash
set -euo pipefail

source "$(dirname "$0")/bw-session.sh"

KEYMAP_FILE="$(dirname "$0")/ssh-key-map.json"
SSH_DIR="$HOME/.ssh"
SSH_CONFIG="$SSH_DIR/config"

mkdir -p "$SSH_DIR"
chmod 700 "$SSH_DIR"

echo "# Auto-generated by dotfiles/secure/ssh-import.sh" > "$SSH_CONFIG"

echo "🔑 Importing all SSH keys defined in $KEYMAP_FILE"

jq -r 'keys[]' "$KEYMAP_FILE" | while read -r service; do
  echo "➡️  $service"

  jq -c ".\"$service\" | to_entries[]" "$KEYMAP_FILE" | while read -r item; do
    keytype=$(echo "$item" | jq -r '.key')
    bw_item=$(echo "$item" | jq -r '.value.bitwarden_item')
    filename=$(echo "$item" | jq -r '.value.file')
    key_path="$SSH_DIR/$filename"

    if [[ "$bw_item" == "null" || "$filename" == "null" ]]; then
      echo "❌ Skipping $service:$keytype → Invalid or missing fields"
      continue
    fi

    echo "  • Fetching $keytype key from \"$bw_item\"..."
    bw_sess get item "$bw_item" | jq -r '.sshKey.privateKey' > "$key_path"
    chmod 600 "$key_path"
    echo "    ↳ Saved to $key_path"

    # If ssh_config is defined and generate_entry is true, append config
    ssh_config=$(echo "$item" | jq -r '.value.ssh_config // empty')

    if [[ -n "$ssh_config" ]] && echo "$ssh_config" | jq -e '.generate_entry == true' >/dev/null 2>&1; then
      host=$(echo "$ssh_config" | jq -r '.host')
      user=$(echo "$ssh_config" | jq -r '.user // "git"')

      if [[ "$host" != "null" ]]; then
        echo "    ↳ Writing SSH config for $host"
        cat <<EOF >> "$SSH_CONFIG"

Host $host
  HostName $host
  User $user
  IdentityFile $key_path
  IdentitiesOnly yes
EOF
      fi
    fi
  done
done

chmod 600 "$SSH_CONFIG"
echo "✅ SSH keys imported and ssh_config generated."
